### PR TITLE
Gh actions

### PR DESCRIPTION
**Pull request by mhesselbarth**
I updated the GH actions a little bit. For now, they will 100% fail, but it's always a bit try-and-error. 

1) I added a Render-README action. Given that the packages uses a `README.Rmd`, the usual practice is to only modify the `.Rmd` file and have the `.md` file rendered automatically by the gh-action. The action is triggerd each time `README.Rmd` is modified.

2) I prepared a codecov gh-action that automatically test to %code that is currently covered by the `testthat` files. This will definitly fail since you need to active the repo on codecov.io

3) I combined all three major OS into one R-CMD check. I think this is easier to maintain and monitor since not three files must be touched each time it fails. In the Actions tab, it will still be visible which OS is failing.

### CODE REVIEW

**Comment by Martin-Jung** [comment]
1) Great, I usually modified the README.rmd and knitted it manually. Having an action is obviously way better
2) Yes, I thought about that, but did not implement it since the repo was not public until recently (and codecov does not work on private repos). I activated the repo on codecov
3) Huh ok. I actually had them into one before and split them simply because it was easier to identify that way which one was failing (for example MacOS required a different library to be installed)

**Comment by mhesselbarth** [comment]
3. I usually prefer to have them combined and work with if statements for the OS. But tbh, I am realizing that's totally personal taste/opinion. So please feel free to delete again if you prefer separate files.

**Comment by mhesselbarth** [comment]
I have a few more smaller changes on this branch to fix some R-CMD warnings/errors. Probably will open a new PR a little later.

**Comment by Martin-Jung** [comment]
3. I just split them to debug them back then. Debugging GH actions caused me a lot of pain... Totally fine with having them more organized

With smaller changes, I just gave you maintain permissions for the repository so feel free to commit to the dev branch (or make your own dev branch)

**Comment by mhesselbarth** [comment]
3. I hate it :) I have in all my packages 23491 commits in which I just start to swear a lot at one point...

**Comment by Martin-Jung** [comment]
3. I wondered that thing before. Apparently there is a way to run GH actions locally, but I have never tried it. https://github.com/nektos/act

**Comment by mhesselbarth** [comment]
I have looked at this before as well but was too lazy to setup the docker ... 🙈

**Pull request merged**
